version: '3'
services:
    web:
        build: .
        ports:
            - 127.0.0.1:8000:8000
        restart: always
        depends_on:
            - db
    db:
        image: postgres:9.6
        volumes:
            # - "./postgres-data:/var/lib/postgresql/data"
            - pgdata:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=time
    migrations:
        build: .
        command: ["./wait-for-it.sh", "db:5432", "--", "flask", "db", "upgrade"]
        depends_on:
            - db

volumes:
    pgdata:
        driver: local
